"""
App Registry - Danh sách tất cả ứng dụng có thể tải
"""

PYTHON_VERSIONS = ["3.13.16", "3.13.0", "3.12.10", "3.12.7", "3.11.9", "3.10.11"]

APPS = [
    {
        "id": "chrome",
        "name": "Google Chrome",
        "description": "Trình duyệt web nhanh, bảo mật",
        "category": "Browser",
        "size": "~160 MB",
        "icon_char": "🌐",
        "color": "#4285F4",
        "url": "https://dl.google.com/chrome/install/standalonesetup64.exe",
        "filename": "ChromeStandaloneSetup64.exe",
        "install_args": ["/silent", "/install"],
        "checked_default": True,
    },
    {
        "id": "vscode",
        "name": "VS Code",
        "description": "Code editor mạnh mẽ, nhẹ",
        "category": "Development",
        "size": "~80 MB",
        "icon_char": "💻",
        "color": "#007ACC",
        "url": "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-user",
        "filename": "VSCodeSetup.exe",
        "install_args": ["/verysilent", "/suppressmsgboxes", "/mergetasks=!runcode"],
        "checked_default": True,
    },
    {
        "id": "git",
        "name": "Git",
        "description": "Hệ thống quản lý version code",
        "category": "Development",
        "size": "~66 MB",
        "icon_char": "🔀",
        "color": "#F05032",
        "url": "https://github.com/git-for-windows/git/releases/download/v2.56.0.windows.1/Git-2.56.0-64-bit.exe",
        "filename": "Git-64-bit.exe",
        "install_args": ["/VERYSILENT", "/NORESTART"],
        "checked_default": True,
    },
    {
        "id": "python",
        "name": "Python",
        "description": "Ngôn ngữ lập trình đa năng",
        "category": "Development",
        "size": "~25 MB",
        "icon_char": "🐍",
        "color": "#3776AB",
        "url": "https://www.python.org/ftp/python/{version}/python-{version}-amd64.exe",
        "filename": "python-{version}-amd64.exe",
        "install_args": ["/quiet", "InstallAllUsers=1", "PrependPath=1"],
        "has_version_select": True,
        "versions": PYTHON_VERSIONS,
        "default_version": "3.12.10",
        "checked_default": True,
    },
    {
        "id": "winrar",
        "name": "WinRAR",
        "description": "Phần mềm nén và giải nén file",
        "category": "Utilities",
        "size": "~4 MB",
        "icon_char": "📦",
        "color": "#8B5CF6",
        "url": "https://www.win-rar.com/fileadmin/winrar-versions/winrar/winrar-x64-723.exe",
        "filename": "winrar-x64.exe",
        "install_args": ["/S"],
        "checked_default": True,
    },
    {
        "id": "visual_studio",
        "name": "Visual Studio",
        "description": "IDE toàn năng của Microsoft",
        "category": "Development",
        "size": "~4 MB (bootstrapper)",
        "icon_char": "🏗️",
        "color": "#5C2D91",
        "url": "https://aka.ms/vs/17/release/vs_community.exe",
        "filename": "VisualStudioSetup.exe",
        "install_args": ["--passive", "--norestart"],
        "checked_default": False,
    },
    {
        "id": "docker",
        "name": "Docker Desktop",
        "description": "Nền tảng container hóa ứng dụng",
        "category": "Development",
        "size": "~600 MB",
        "icon_char": "🐋",
        "color": "#2496ED",
        "url": "https://desktop.docker.com/win/main/amd64/Docker%20Desktop%20Installer.exe",
        "filename": "DockerDesktopInstaller.exe",
        "install_args": ["install", "--quiet"],
        "requires_wsl": True,   # chạy `wsl --install` trước khi cài
        "checked_default": False,
    },
    {
        "id": "zalo",
        "name": "Zalo",
        "description": "Nhắn tin, gọi điện miễn phí",
        "category": "Communication",
        "size": "~180 MB",
        "icon_char": "💬",
        "color": "#0068FF",
        "url": "https://zalo.me/download/zalo-pc",
        "filename": "ZaloSetup.exe",
        "install_args": ["/S"],
        "checked_default": True,
    },
]

CATEGORIES = {
    "Browser":       {"label": "Trình duyệt",  "color": "#4A90D9"},
    "Development":   {"label": "Phát triển",   "color": "#4A90D9"},
    "Utilities":     {"label": "Tiện ích",      "color": "#7a90c8"},
    "Communication": {"label": "Liên lạc",      "color": "#0068FF"},
}
